//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UFS_Application.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionApprovalStatusDetail
    {
        public int RequisitionApprovalStatusId { get; set; }
        public Nullable<int> RequisitionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public string Comments { get; set; }
        public byte[] VersionNo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Requisition Requisition { get; set; }
        public virtual User User { get; set; }
    }
}
