//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UFS_Application.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requisition()
        {
            this.Requisition_Detail = new HashSet<Requisition_Detail>();
            this.RequisitionApprovalStatusDetails = new HashSet<RequisitionApprovalStatusDetail>();
            this.RequisitionAttachements = new HashSet<RequisitionAttachement>();
            this.RequisitionPopCodes = new HashSet<RequisitionPopCode>();
            this.RequisitionSKUDetails = new HashSet<RequisitionSKUDetail>();
        }
    
        public int RequisitionId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> FunctionId { get; set; }
        public string Geography { get; set; }
        public Nullable<System.DateTime> FromTime { get; set; }
        public Nullable<System.DateTime> ToTime { get; set; }
        public string CustomerBackground { get; set; }
        public string BrandUserCustomer { get; set; }
        public string PromotionDesc { get; set; }
        public string SKUDetail { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> ROI { get; set; }
        public Nullable<decimal> GM { get; set; }
        public Nullable<decimal> MinGSV { get; set; }
        public Nullable<decimal> MaxGSV { get; set; }
        public Nullable<decimal> MinTTS { get; set; }
        public Nullable<decimal> MaxTTS { get; set; }
        public string RequestorComments { get; set; }
        public string RegionHeadComments { get; set; }
        public string FBPComments { get; set; }
        public string MFComments { get; set; }
        public string CHComments { get; set; }
        public byte[] VersionNo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> TotalMinQtyMonthCases { get; set; }
        public Nullable<int> TotalMaxQtyMonthCases { get; set; }
        public Nullable<int> RequisitionStatus { get; set; }
        public string Comments { get; set; }
        public bool IsTerminationRequested { get; set; }
        public Nullable<int> RequisitionCounter { get; set; }
        public Nullable<bool> IsNewUser { get; set; }
        public string ExistingGM { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Function Function { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requisition_Detail> Requisition_Detail { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionApprovalStatusDetail> RequisitionApprovalStatusDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionAttachement> RequisitionAttachements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionPopCode> RequisitionPopCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionSKUDetail> RequisitionSKUDetails { get; set; }
    }
}
