//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UFS_Application.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UFSEntitiess : DbContext
    {
        public UFSEntitiess()
            : base("name=UFSEntitiess")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Requisition> Requisitions { get; set; }
        public virtual DbSet<Requisition_Detail> Requisition_Detail { get; set; }
        public virtual DbSet<RequisitionApprovalStatusDetail> RequisitionApprovalStatusDetails { get; set; }
        public virtual DbSet<RequisitionAttachement> RequisitionAttachements { get; set; }
        public virtual DbSet<RequisitionPopCode> RequisitionPopCodes { get; set; }
        public virtual DbSet<RequisitionSKUDetail> RequisitionSKUDetails { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<V_RequisitionByCustomerWise> V_RequisitionByCustomerWise { get; set; }
        public virtual DbSet<v_RequisitionBySku> v_RequisitionBySku { get; set; }
        public virtual DbSet<v_RequisitionBySku_OLD> v_RequisitionBySku_OLD { get; set; }
    
        public virtual ObjectResult<Categorized_DashBaord_Result> Categorized_DashBaord()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Categorized_DashBaord_Result>("Categorized_DashBaord");
        }
    
        public virtual ObjectResult<GetRequisitionAuditById_Result> GetRequisitionAuditById(Nullable<int> requisitionId)
        {
            var requisitionIdParameter = requisitionId.HasValue ?
                new ObjectParameter("RequisitionId", requisitionId) :
                new ObjectParameter("RequisitionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRequisitionAuditById_Result>("GetRequisitionAuditById", requisitionIdParameter);
        }
    
        public virtual ObjectResult<StoredProcedure_RequisitionSummary_Result> StoredProcedure_RequisitionSummary()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StoredProcedure_RequisitionSummary_Result>("StoredProcedure_RequisitionSummary");
        }
    }
}
