//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UFS_Application.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RequisitionByCustomerWise
    {
        public Nullable<long> SrNo { get; set; }
        public int RequisitionId { get; set; }
        public string FunctionName { get; set; }
        public string CreatedDate { get; set; }
        public string ContractStartDate { get; set; }
        public string ContractEndDate { get; set; }
        public string CustomerName { get; set; }
        public string Region { get; set; }
        public string Background { get; set; }
        public string ObjectiveAndDescription { get; set; }
        public string TM_AM { get; set; }
        public string RequestorComments { get; set; }
        public string GSM { get; set; }
        public string GSMMessage { get; set; }
        public string FinanceBusinessPartner { get; set; }
        public string FinanceBusinessPartnerMessage { get; set; }
        public string ManagerFinance { get; set; }
        public string ManagerFinanceMessage { get; set; }
        public string CountryHeadUFS { get; set; }
        public string CountryHeadUFSMessage { get; set; }
        public Nullable<decimal> MinGSV { get; set; }
        public Nullable<decimal> MaxGSV { get; set; }
        public Nullable<decimal> MinTTS { get; set; }
        public Nullable<decimal> MaxTTS { get; set; }
        public string Decision { get; set; }
        public string Deleted { get; set; }
        public string CurrentStatus { get; set; }
        public string PopCode { get; set; }
    }
}
