//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UFS_Application.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_RequisitionBySku_OLD
    {
        public string SrNo { get; set; }
        public Nullable<long> RowNum { get; set; }
        public Nullable<long> Rank { get; set; }
        public int RequisitionId { get; set; }
        public string FunctionName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> Contract_Start_Date { get; set; }
        public Nullable<System.DateTime> Contract_End_Date { get; set; }
        public string Customer_Name { get; set; }
        public string Region { get; set; }
        public string SKUName { get; set; }
        public string SKUCode { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> Minimum_Quantity { get; set; }
        public Nullable<int> Maximum_Quantity { get; set; }
        public string PromotionCode { get; set; }
        public string TM_AM { get; set; }
        public string GSM { get; set; }
        public string GSMMessage { get; set; }
        public string FinanceBusinessPartner { get; set; }
        public string FinanceBusinessPartnerMessage { get; set; }
        public string ManagerFinance { get; set; }
        public string ManagerFinanceMessage { get; set; }
        public string CountryHeadUFS { get; set; }
        public string CountryHeadUFSMessage { get; set; }
        public string Status { get; set; }
        public string UserComments { get; set; }
        public string PopCode { get; set; }
    }
}
